import React, { useMemo, useState } from "react";
import { ArrowDown, ArrowRight, Check, ChevronLeft, ChevronRight, Database, RotateCcw, X } from "lucide-react";
import { Badge, LinkCard, SectionHead } from "./common";

type Mode="mha"|"mqa"|"gqa";
const MODES:{id:Mode;name:string;kv:number;desc:string}[]=[
  {id:"mha",name:"MHA",kv:8,desc:"8 个查询头各带一组 K、V"},
  {id:"gqa",name:"GQA",kv:2,desc:"8 个查询头分组共享 2 组 K、V"},
  {id:"mqa",name:"MQA",kv:1,desc:"8 个查询头共同使用 1 组 K、V"},
];
const Q_COLORS=["bg-coral","bg-teal","bg-butter","bg-pop","bg-coral","bg-teal","bg-butter","bg-pop"];

const HeadDiagram:React.FC<{mode:Mode;compact?:boolean}>=({mode,compact})=>{
  const meta=MODES.find(item=>item.id===mode)!;
  return <div className="min-w-0"><div className="grid grid-cols-8 gap-1.5">{Array.from({length:8},(_,index)=><div key={index} className={`${Q_COLORS[index]} ${index%4===1||index%4===3?"text-cream":""} flex ${compact?"h-10":"h-14"} items-center justify-center rounded-lg border-2 border-ink font-mono text-xs font-bold`}>Q{index+1}</div>)}</div><div className="my-3 flex justify-center"><ArrowDown className="h-5 w-5"/></div><div className={`grid gap-2 ${meta.kv===8?"grid-cols-8":meta.kv===2?"grid-cols-2":"grid-cols-1"}`}>{Array.from({length:meta.kv},(_,index)=><div key={index} className="rounded-xl border-2 border-ink bg-white px-2 py-3 text-center font-mono text-[11px] font-bold shadow-stamp">K{index+1} · V{index+1}</div>)}</div></div>;
};

export const SectionMqaHero:React.FC=()=>{
  const [mode,setMode]=useState<Mode>("mqa");
  const active=MODES.find(item=>item.id===mode)!;
  return <section className="overflow-hidden bg-butter px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-[1160px] gap-12 lg:grid-cols-12 lg:items-center">
    <div className="lg:col-span-6"><div className="eyebrow text-ink/60">Multi-Query Attention · 多查询注意力</div><h1 className="mt-5 font-display text-display-xl font-extrabold">MQA 是什么？</h1><p className="mt-7 max-w-xl font-display text-[clamp(1.35rem,3vw,2.05rem)] font-bold leading-[1.3]"><span className="box-decoration-clone bg-coral px-2 text-cream">MQA = 多头注意力的一种改法，保留多个查找角度，减少生成时要保存的数据。</span></p><div className="mt-7 max-w-xl space-y-4 text-[16px] leading-[1.8] text-ink/80"><p>多头注意力会同时用多个角度查找信息，每个角度叫一个查询头。工程里把匹配线索叫 K，把可取信息叫 V。</p><p>MQA 让多个查询头共用一组 K、V。先对比 MHA（多头注意力）和 MQA；GQA（分组查询注意力）是两者之间的折中。</p></div><a href="../multi-head-attention/index.html" className="mt-6 block max-w-xl rounded-2xl border-2 border-ink bg-white px-4 py-3 text-sm font-bold shadow-stamp transition-all hover:-translate-x-0.5 hover:-translate-y-0.5">如果“查询头”还不熟，先看多头注意力 →</a><p className="mt-8 inline-flex items-center gap-2 font-mono text-xs font-bold tracking-[.12em]">先看共享发生在哪里 <ArrowDown className="h-4 w-4"/></p></div>
    <div className="lg:col-span-6"><div className="rounded-[2rem] border-2 border-ink bg-cream p-5 shadow-stamp-xl lg:p-7"><div className="flex gap-2">{MODES.filter(item=>item.id!=="gqa").map(item=><button key={item.id} onClick={()=>setMode(item.id)} className={`flex-1 rounded-xl border-2 border-ink px-3 py-2 font-mono text-sm font-bold ${mode===item.id?"bg-ink text-cream shadow-stamp":"bg-white"}`}>{item.name}</button>)}</div><div key={mode} className="mt-7 animate-enter-fade"><HeadDiagram mode={mode}/><p className="mt-5 rounded-xl border-2 border-ink bg-white p-3 text-sm font-bold">{active.desc}</p></div></div></div>
  </div></section>
};

export const SectionStructureSwitch:React.FC=()=>{
  const [mode,setMode]=useState<Mode>("mha");
  const [heads,setHeads]=useState(8);
  const kv=mode==="mha"?heads:mode==="mqa"?1:Math.max(1,Math.round(heads/4));
  return <section className="px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1140px]"><SectionHead number="02" label="谁共享，谁保留" title={<>Q 头仍然有很多个，<br/>共享的是 K 和 V</>} intro={<p>“Multi-Query”这个名字容易让人误会。它保留多个 Query 头，每个头都有自己的 Q。K、V 的头数被压到一组。</p>}/>
    <div className="grid gap-6 lg:grid-cols-12"><div className="card-stamp p-5 lg:col-span-4"><h3 className="font-display text-xl font-bold">切换并比较三种结构</h3><div className="mt-5 space-y-2">{MODES.map(item=><button key={item.id} onClick={()=>setMode(item.id)} className={`w-full rounded-xl border-2 border-ink p-3 text-left ${mode===item.id?"bg-ink text-cream shadow-stamp":"bg-white"}`}><span className="font-mono text-xs font-bold">{item.name}</span><span className="mt-1 block text-sm opacity-75">{item.desc}</span></button>)}</div><label className="mt-6 block"><span className="flex justify-between text-sm font-bold"><span>查询头数量</span><span>{heads}</span></span><input type="range" min={4} max={16} step={4} value={heads} onChange={e=>setHeads(Number(e.target.value))} className="range-control mt-3"/></label></div>
    <div className="rounded-[2rem] border-2 border-ink bg-butter-tint p-5 shadow-stamp-lg lg:col-span-8"><div className="grid gap-6 sm:grid-cols-2"><div><div className="font-mono text-[10px] text-ink/50">QUERY HEADS</div><div className="mt-4 grid grid-cols-4 gap-2">{Array.from({length:heads},(_,index)=><div key={index} className={`${Q_COLORS[index%8]} ${index%4===1||index%4===3?"text-cream":""} flex h-11 items-center justify-center rounded-lg border-2 border-ink font-mono text-[10px] font-bold`}>Q{index+1}</div>)}</div></div><div><div className="font-mono text-[10px] text-ink/50">KEY / VALUE HEADS</div><div className="mt-4 grid grid-cols-2 gap-2">{Array.from({length:kv},(_,index)=><div key={index} className="rounded-xl border-2 border-ink bg-white px-3 py-3 text-center font-mono text-xs font-bold shadow-stamp">K{index+1} · V{index+1}</div>)}</div></div></div><div className="mt-7 rounded-2xl border-2 border-ink bg-white p-4"><span className="font-display text-xl font-bold">{heads} 个 Q 头，{kv} 组 K/V</span><p className="mt-2 text-sm text-ink/65">相对同头数 MHA，K/V 组数保留 {(kv/heads*100).toFixed(0)}%。</p></div></div></div>
  </div></section>
};

const DECODE=["读完用户输入","为前文留下 K、V","生成第一个新 token","多个 Q 头读取共享 K、V","追加新 token 的一组 K、V"];
export const SectionDecodeWalk:React.FC=()=>{
  const [step,setStep]=useState(0);
  const tokens=["今","天","适","合","散","步"];
  const generatedByStep=[0,0,1,1,2];
  const generatedCount=generatedByStep[step];
  const visibleTokens=tokens.slice(0,generatedCount);
  const cachedItems=step===0?[]:["用户输入",...visibleTokens];
  return <section className="border-y-2 border-ink bg-teal px-4 py-20 text-cream sm:px-6 lg:px-8"><div className="mx-auto max-w-[1140px]"><SectionHead inverse number="03" label="逐字生成时发生什么" title={<>每写一个新 token，<br/>所有 Q 头读取同一份前文笔记</>} intro={<p>token 是模型处理的一小段文字。模型会把前文算出的 K、V 暂时存起来，生成下一个 token 时直接读取。这份暂存的计算结果叫 KV Cache。</p>}/>
    <div className="rounded-[2rem] border-2 border-ink bg-cream p-5 text-ink shadow-stamp-xl lg:p-7"><div className="grid gap-2 md:grid-cols-5">{DECODE.map((item,index)=><button key={item} onClick={()=>setStep(index)} className={`rounded-xl border-2 border-ink p-3 text-left text-sm font-bold ${index<=step?"bg-butter shadow-stamp":"bg-white text-ink/40"}`}><span className="block font-mono text-[10px]">STEP {index+1}</span>{item}</button>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-12"><div className="lg:col-span-7"><div className="font-mono text-[10px] text-ink/50">回答正在增长</div><div className="mt-4 flex min-h-[58px] flex-wrap gap-2">{visibleTokens.length===0?<span className="rounded-xl border-2 border-dashed border-ink/35 px-4 py-3 text-sm text-ink/50">还没有生成回答</span>:visibleTokens.map((token,index)=><span key={index} className={`rounded-xl border-2 border-ink px-4 py-3 font-display text-xl font-bold ${index===visibleTokens.length-1?"bg-coral text-cream shadow-stamp":"bg-white"}`}>{token}</span>)}</div><div className="mt-7 grid grid-cols-4 gap-2">{Array.from({length:8},(_,index)=><div key={index} className={`${Q_COLORS[index]} ${index%4===1||index%4===3?"text-cream":""} rounded-lg border-2 border-ink p-2 text-center font-mono text-[10px] font-bold`}>Q{index+1}</div>)}</div></div><div className="lg:col-span-5"><div className="rounded-3xl border-2 border-ink bg-ink p-5 text-cream shadow-stamp"><Database className="h-7 w-7 text-butter"/><div className="mt-4 font-display text-xl font-bold">共享 KV Cache</div><div className="mt-4 flex min-h-[30px] flex-wrap gap-2">{cachedItems.length===0?<span className="text-sm text-cream/45">等待处理输入</span>:cachedItems.map((item,index)=><span key={`${item}-${index}`} className="rounded-lg border-2 border-cream bg-teal px-2 py-1 font-mono text-[10px]">K·V {item}</span>)}</div><p className="mt-4 text-sm text-cream/70">每个历史位置只留一组 K、V，多个 Q 头反复读取它们。</p></div></div></div><div className="mt-7 flex gap-3"><button onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0} className="btn-stamp bg-white disabled:opacity-40"><ChevronLeft className="h-4 w-4"/>上一步</button><button onClick={()=>setStep(Math.min(DECODE.length-1,step+1))} disabled={step===DECODE.length-1} className="btn-stamp bg-butter disabled:opacity-40">下一步<ChevronRight className="h-4 w-4"/></button><button onClick={()=>setStep(0)} className="btn-stamp bg-white px-3" aria-label="重来"><RotateCcw className="h-4 w-4"/></button></div></div>
  </div></section>
};

export const SectionCacheCalculator:React.FC=()=>{
  const [context,setContext]=useState(8192);
  const [heads,setHeads]=useState(32);
  const [users,setUsers]=useState(8);
  const [mode,setMode]=useState<Mode>("mqa");
  const kvHeads=mode==="mha"?heads:mode==="mqa"?1:Math.max(1,Math.round(heads/8));
  const base=context*heads*users;
  const current=context*kvHeads*users;
  const relative=current/base;
  return <section className="bg-butter-tint px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1140px]"><SectionHead number="04" label="缓存为什么会变小" title={<>上下文越长、请求越多，<br/>共享 K、V 越能省空间</>} intro={<p>KV Cache 大小会跟历史长度、K/V 头数和同时生成的请求数一起增长。这里固定其他模型参数，只看结构带来的相对变化。</p>}/>
    <div className="grid gap-6 lg:grid-cols-12"><div className="card-stamp p-6 lg:col-span-5"><div className="flex items-center justify-between"><h3 className="font-display text-xl font-bold">调整生成场景</h3><Badge/></div>{[{label:"上下文长度",value:context,min:1024,max:32768,step:1024,display:`${context/1024}K`,set:setContext},{label:"查询头数量",value:heads,min:8,max:64,step:8,display:`${heads} 个`,set:setHeads},{label:"同时生成请求",value:users,min:1,max:32,step:1,display:`${users} 个`,set:setUsers}].map(item=><label key={item.label} className="mt-6 block"><span className="flex justify-between text-sm font-bold"><span>{item.label}</span><span>{item.display}</span></span><input type="range" min={item.min} max={item.max} step={item.step} value={item.value} onChange={e=>item.set(Number(e.target.value))} className="range-control mt-3"/></label>)}<div className="mt-6 grid grid-cols-3 gap-2">{MODES.map(item=><button key={item.id} onClick={()=>setMode(item.id)} className={`rounded-xl border-2 border-ink p-2 font-mono text-xs font-bold ${mode===item.id?"bg-ink text-cream shadow-stamp":"bg-white"}`}>{item.name}</button>)}</div></div>
    <div className="rounded-[2rem] border-2 border-ink bg-white p-6 shadow-stamp-lg lg:col-span-7"><div className="font-mono text-[10px] text-ink/50">相对同配置 MHA 的 K/V 缓存</div><div className="mt-2 font-display text-6xl font-black">{(relative*100).toFixed(1)}%</div><div className="mt-6 h-12 overflow-hidden rounded-2xl border-2 border-ink bg-cream"><div className="h-full bg-coral transition-all duration-250" style={{width:`${Math.max(2,relative*100)}%`}}/></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border-2 border-ink bg-butter p-4"><div className="font-mono text-[10px]">Q HEADS</div><div className="font-display text-2xl font-bold">{heads}</div></div><div className="rounded-2xl border-2 border-ink bg-teal p-4 text-cream"><div className="font-mono text-[10px]">KV HEADS</div><div className="font-display text-2xl font-bold">{kvHeads}</div></div><div className="rounded-2xl border-2 border-ink bg-coral p-4 text-cream"><div className="font-mono text-[10px]">示意数据格</div><div className="font-display text-2xl font-bold">{(current/10000).toFixed(1)} 万</div></div></div><p className="mt-5 text-sm leading-relaxed text-ink/60">示意计算只比较 K/V 头数造成的差异，不代表具体模型的 GB 数。真实占用还取决于层数、每头宽度和数字精度。</p></div></div>
  </div></section>
};

export const SectionTradeoff:React.FC=()=>{
  const [mode,setMode]=useState<Mode>("gqa");
  const [answers,setAnswers]=useState<Record<number,boolean>>({});
  const meta={mha:{speed:45,memory:20,flex:95},gqa:{speed:82,memory:78,flex:82},mqa:{speed:95,memory:96,flex:65}}[mode];
  const facts=[{text:"MQA 主要减少逐字生成时读取 K、V 的负担。",right:true},{text:"共享 K、V 后，Q 头也只剩一个。",right:false},{text:"GQA 用多组 K、V，落在 MHA 与 MQA 之间。",right:true}];
  return <section className="px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1140px]"><SectionHead number="05" label="速度和表达能力的取舍" title={<>共享越多，缓存越省；<br/>各头可用的 K、V 也越相似</>} intro={<p>MQA 能明显减小 K/V 数据，也可能带来质量损失。GQA 让一小组查询头共享一组 K、V，常用来取得中间平衡。</p>}/>
    <div className="grid gap-6 lg:grid-cols-12"><div className="card-stamp p-5 lg:col-span-5"><div className="grid grid-cols-3 gap-2">{MODES.map(item=><button key={item.id} onClick={()=>setMode(item.id)} className={`rounded-xl border-2 border-ink p-3 font-mono text-xs font-bold ${mode===item.id?"bg-ink text-cream shadow-stamp":"bg-white"}`}>{item.name}</button>)}</div>{[["生成速度",meta.speed],["缓存余量",meta.memory],["每头独立程度",meta.flex]].map(([label,value])=><div key={label as string} className="mt-6"><div className="mb-2 flex justify-between text-sm font-bold"><span>{label}</span><span>{value}%</span></div><div className="h-4 overflow-hidden rounded-full border-2 border-ink bg-cream"><div className="h-full bg-coral transition-all duration-250" style={{width:`${value}%`}}/></div></div>)}<p className="mt-5 text-xs leading-relaxed text-ink/50">三条数值是教学示意，只表达结构取舍方向，不是模型评测结果。</p></div>
    <div className="space-y-3 lg:col-span-7">{facts.map((fact,index)=>{const answered=index in answers;const correct=answers[index]===fact.right;return <div key={fact.text} className="rounded-2xl border-2 border-ink bg-white p-4 shadow-stamp"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><p className="flex-1 font-display text-lg font-bold">{fact.text}</p><div className="flex gap-2"><button onClick={()=>setAnswers(cur=>({...cur,[index]:true}))} className="btn-stamp bg-butter px-3"><Check className="h-4 w-4"/>对</button><button onClick={()=>setAnswers(cur=>({...cur,[index]:false}))} className="btn-stamp bg-white px-3"><X className="h-4 w-4"/>不对</button></div></div>{answered&&<p className={`mt-4 rounded-xl border-2 border-ink p-3 text-sm font-bold ${correct?"bg-teal text-cream":"bg-coral text-cream"}`}>{correct?"判断正确":`应选「${fact.right?"对":"不对"}」`}</p>}</div>})}</div></div>
  </div></section>
};

export const SectionMqaNext:React.FC=()=> <section className="bg-butter-tint px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1140px]"><SectionHead number="06" label="三个概念分别解决什么问题" title={<>Attention 决定看哪里，<br/>多头扩展角度，MQA 减少重复的 K/V</>} intro={<p>Attention 负责挑重点，MHA 同时运行多组 Attention，MQA 在 MHA 的基础上共享 K、V，减少生成时的数据读取。</p>}/><div className="grid gap-5 md:grid-cols-3"><LinkCard href="../attention/index.html" title="注意力机制" desc="回看 Q、K、V 和权重怎样完成一次信息查找。"/><LinkCard href="../multi-head-attention/index.html" title="Multi-Head Attention" desc="回看多个头怎样独立计算再合并。"/><LinkCard href="../kv-cache/index.html" title="KV Cache" desc="继续看 K、V 怎样随生成增长，以及缓存为何会占显存。"/></div><div className="mt-8 rounded-3xl border-2 border-ink bg-ink p-6 text-cream shadow-stamp"><div className="font-mono text-[10px] tracking-[.16em] text-butter-soft">本章结论</div><p className="mt-2 font-display text-2xl font-bold">MQA 保留多个 Q 头，同时让它们共享一组 K、V。</p><p className="mt-3 font-mono text-[10px] text-cream/55">资料：Shazeer, Fast Transformer Decoding, 2019 · arXiv:1911.02150；Ainslie et al., GQA, 2023 · arXiv:2305.13245</p></div></div></section>;
