// Concatenates all themes/<id>/tokens.css files from the
// web-video-presentation skill into a single src/styles/themes.gen.css.
// Each `:root { ... }` block is rewritten as `[data-theme="<id>"] { ... }`
// so the same demo page can render any theme by toggling the attribute.

import {
  existsSync,
  readdirSync,
  readFileSync,
  writeFileSync,
  statSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "..");
const THEMES_DIR = resolve(
  ROOT,
  "..",
  "..",
  "skills",
  "web-video-presentation",
  "themes",
);
const OUT = resolve(ROOT, "src", "styles", "themes.gen.css");
const MANIFEST_OUT = resolve(ROOT, "src", "themes.manifest.gen.json");

if (!existsSync(THEMES_DIR)) {
  if (existsSync(OUT) && existsSync(MANIFEST_OUT)) {
    console.warn(
      `themes source not found at ${THEMES_DIR}; keeping existing generated theme assets.`,
    );
    process.exit(0);
  }

  throw new Error(
    `themes source not found at ${THEMES_DIR}, and generated theme assets are missing.`,
  );
}

function listThemes() {
  return readdirSync(THEMES_DIR)
    .filter((name) => {
      const p = join(THEMES_DIR, name);
      return statSync(p).isDirectory();
    })
    .sort();
}

const parts = [
  "/* AUTO-GENERATED by scripts/build-themes.mjs — do not edit. */",
  "/* Source: skills/web-video-presentation/themes/<id>/tokens.css      */",
  "",
];
const manifest = [];

for (const id of listThemes()) {
  const tokensPath = join(THEMES_DIR, id, "tokens.css");
  const metaPath = join(THEMES_DIR, id, "theme.json");
  let css;
  try {
    css = readFileSync(tokensPath, "utf8");
  } catch {
    continue;
  }
  // Rewrite the single :root block to a scoped selector. Themes only
  // ever have one :root in their tokens.css.
  const scoped = css.replace(/:root\s*\{/, `[data-theme="${id}"] {`);
  parts.push(`/* ────── ${id} ────── */`);
  parts.push(scoped.trim());
  parts.push("");

  try {
    const meta = JSON.parse(readFileSync(metaPath, "utf8"));
    manifest.push({
      id,
      name: meta.name ?? id,
      nameZh: meta.nameZh ?? meta.name ?? id,
      description: meta.description ?? "",
      descriptionZh: meta.descriptionZh ?? "",
      mood: meta.mood ?? [],
      bestFor: meta.bestFor ?? [],
      preview: meta.preview ?? {},
    });
  } catch {
    manifest.push({ id, name: id, nameZh: id });
  }
}

writeFileSync(OUT, parts.join("\n"));
writeFileSync(
  MANIFEST_OUT,
  JSON.stringify(manifest, null, 2) + "\n",
);
console.log(`✓ wrote ${OUT} (${manifest.length} themes)`);
